Refactor config lock and optimize parallel process logic
zhenghaoz/gorse pull request #354
Opened 2022-01-11 11:39 UTC by winwill2012

There are two changes:
1.  Refactor config lock ;
2. in parallel.go, if any error occurred in go routine loop, whole loop will exit. I think it is not reasonable, so remove `return`.

2022-01-11 12:01 UTC, Somiacao requested changes
感谢贡献:smile:，对base/parallel.go的修改没有问题，但是对于配置文件的修改我们还需要讨论下

2022-01-11 12:01 UTC, Somiacao commented on config/config.go
> +type ExploreWrapper struct {
非常感谢您的贡献，这个配置文件格式的修改是基于什么考虑呢。😂毕竟配置文件修改属于破坏更新，小版本升级要避免修改

2022-01-11 12:09 UTC, Somiacao commented on config/config.go
> +type ExploreWrapper struct {
😂毕竟配置文件修改属于破坏更新，小版本升级要避免修改

2022-01-12 01:04 UTC, winwill2012 commented on config/config.go
> +type ExploreWrapper struct {
嗯 是我的疏忽，配置相关的改动我先回滚吧，感谢

2022-01-12 01:04 UTC, closed without merging

2022-01-12 01:06 UTC, winwill2012 commented
先不合并